# Generated by Django 4.1.5 on 2023-03-15 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('User_Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Otp', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'OTP',
            },
        ),
        migrations.CreateModel(
            name='Sem_Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Working_Days', models.IntegerField()),
                ('Date', models.DateField()),
            ],
            options={
                'db_table': 'Sem_Days',
            },
        ),
        migrations.CreateModel(
            name='Staff_Details',
            fields=[
                ('User_Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Staff_ID', models.CharField(max_length=50, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Phone_Number', models.BigIntegerField()),
                ('Mail_ID', models.EmailField(max_length=254, unique=True)),
                ('Photo', models.ImageField(upload_to='Staff_Images/')),
            ],
            options={
                'db_table': 'Staff_Details',
            },
        ),
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('User_Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Regno', models.CharField(max_length=100, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=50)),
                ('Degree', models.CharField(max_length=100)),
                ('Year', models.CharField(default='N/A', max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Phone_Number', models.BigIntegerField()),
                ('Mail_ID', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'Student_Details',
            },
        ),
        migrations.CreateModel(
            name='Students_Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Regno', models.CharField(max_length=100, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Phone_Number', models.BigIntegerField()),
                ('Degree', models.CharField(max_length=100)),
                ('Attendance', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'Students_Backup',
            },
        ),
        migrations.CreateModel(
            name='Students_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_ID', models.CharField(max_length=100)),
                ('Student_Name', models.CharField(max_length=100)),
                ('Degree', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('HR_1', models.CharField(max_length=10)),
                ('HR_2', models.CharField(max_length=10)),
                ('HR_3', models.CharField(max_length=10)),
                ('HR_4', models.CharField(max_length=10)),
                ('HR_5', models.CharField(max_length=10)),
                ('Student_Regno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance_Log.student_details', to_field='Regno')),
            ],
            options={
                'db_table': 'Students_Attendance',
            },
        ),
    ]
