# Generated by Django 3.2.16 on 2023-03-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_Log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_backup',
            name='Attendance',
            field=models.JSONField(default=dict),
        ),
    ]
