# Generated by Django 3.2.16 on 2023-03-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_Log', '0002_alter_students_backup_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_backup',
            name='Attendance',
            field=models.TextField(),
        ),
    ]
