# Generated by Django 3.2.18 on 2023-03-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_Log', '0003_alter_students_backup_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_backup',
            name='Attendance',
            field=models.JSONField(default=dict),
        ),
    ]
