# Generated by Django 5.1.7 on 2025-07-28 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_Log', '0004_alter_students_backup_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facial_Students_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Face_id', models.CharField(max_length=10)),
                ('Student_Name', models.CharField(max_length=100)),
                ('Degree', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('HR_1', models.CharField(max_length=10)),
                ('HR_2', models.CharField(max_length=10)),
                ('HR_3', models.CharField(max_length=10)),
                ('HR_4', models.CharField(max_length=10)),
                ('HR_5', models.CharField(max_length=10)),
                ('Student_Regno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance_Log.student_details', to_field='Regno')),
            ],
            options={
                'db_table': 'Facial_Students_Attendance',
            },
        ),
    ]
