# Generated by Django 5.1.7 on 2025-07-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_Log', '0005_facial_students_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facial_students_attendance',
            name='Student_Regno',
            field=models.CharField(max_length=100),
        ),
    ]
